// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:47c9c0d4-e099-4f64-9155-da5022ca9abd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lXcim5Yo1",
    "aws_user_pools_web_client_id": "1htccvmpak14khb9qdus2egik2",
    "aws_appsync_graphqlEndpoint": "https://borrilbx2vcafmlerpfyudjnhi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "amplifychatroom-20181120143705--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://amplifychatroom-20181120143705--hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
